services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free  # Change if you need more resources
    region: oregon  # Choose a region closer to your users
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false  # You will add this manually in Render